# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e595e4a4c1b2bc06f0cfdbfb29a9de250c1df76151fcdd1645bec615da4a387f47cb66b117973b4c16519a5096085409493f0ac70162ff611bfa1886f7ad947d

test:
  secret_key_base: 49817f0e6ba5630b000ad7b37136c36ae670ac12179266cd2288866ae70a1def372f4c652541f3978552bb87f1aef1df5199b8a629e893ab7f01e78303b90c88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
